### ISSUE TITLE
didn't work for me 

### ISSUE THREAD

**Issue by topokhanma** [Zeeshanahmad4/Tiktok-User-Video-Post-Scraper#1]
I'm not a programmer but I want use this script to download all videos from a tiktok account
this is the problem that I have with the script https://imgur.com/a/ZeQ71H8

**Comment by Zeeshanahmad4** [comment]
TikTok recently make some changes to their front-end making it impossible to
Scrape videos. This scraper may not work anymore. I check all the GitHub nothing is working anymore.

**Comment by Zeeshanahmad4** [comment]
I am closing this now.
